### PR TITLE
add data sync cron, s3 sync options and bucket names

### PR DESCRIPTION
**Pull request by klibby**
I think this wraps up the AWS side of #18

### CODE REVIEW

**Comment by gozer** [comment]
yup, looking good.

r=gozer

**Comment by gozer** [comment]
Hrm, thinking back on it, not sure about the safety of using --delete here...

**Comment by klibby** [comment]
We're using it with rsync between SCL3/PHX1 today; it's needed.

**Comment by gozer** [comment]
Yeah, the problem is that as soon as we push that to stage in AWS, it will start nuking data/ until the SCL3 side of things is fixed...

**Comment by gozer** [comment]
Deleting the option for now, so as not to break stage yet, and i've done one manual sync from a stage node into the bucket, so there is data in there too.

**Comment by klibby** [comment]
If you've manually seeded the bucket, then it's safe to leave --delete in, since it should be the same data, no?

**Comment by gozer** [comment]
Not quite, since data/assets are generated on page view, if what I have in data/assets is incomplete, then testing one page will generate the js/css in there, then the sync job will nuke it, resulting in possibly borked pages, no?

**Comment by klibby** [comment]
Yeah, you're right. Carry on!

**Pull request merged**
